### ISSUE TITLE
Can't change prefix key

### ISSUE THREAD

**Issue by Tsoomer** [mpdel/mpdel#18] opened 2024-07-26 16:36 UTC
Regardless of how I set my prefix key I can't get it to actually be used and the default is used instead. My current config is:

`(use-package mpdel
  :ensure t
  :config
  (setq mpdel-prefix-key (kbd "s-m m"))
  (mpdel-mode))`

Thanks for your help in advance!

**Comment by DamienCassou** [comment] 2024-07-27 16:28
The problem is that when loading, `mpdel` uses the value of `mpdel-prefix-key` to create the value for `mpdel-mode-map`. So your change of the prefix key comes too late.

The solution is to set `mpdel-prefix-key` before `mpdel` is loaded. This can be done with `use-package` through the `:init` keyword instead of `:config`:

```emacs
(use-package mpdel
  :ensure t
  :init (setq mpdel-prefix-key (kbd "s-m m"))
  :config (mpdel-mode))
```

I just changed the README in #19 to make that clearer.

I'm closing this issue. Feel free to reopen if your issue persists.

**Closed by DamienCassou** 2024-07-27 16:28 UTC

**Comment by Tsoomer** [comment] 2024-07-27 17:18
Thank you, this worked!
